language: objective-c
osx_image: xcode8.2
xcode_project: SmartCarOAuthSDK.xcodeproj # path to your xcodeproj folder
xcode_scheme: SmartCarOAuthSDK
xcode_sdk: iphonesimulator10.1
script:
- xcodebuild -project SmartCarOAuthSDK.xcodeproj -scheme SmartCarOAuthSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild -project SmartCarOAuthSDK.xcodeproj -scheme SmartCarOAuthSDK -sdk iphonesimulator -destination 'platform=iOS Simulator,id=7B6F8C6B-B67A-4F64-BB70-AE1FF077ACC2,OS=10.2,name=iPhone 7 Plus' build test 